name: flutter_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  video_player: ^2.5.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiramisu.jpg
    - assets/video/tiramisu.mp4

